In [4]:
import torch

a = torch.tensor(1.0)
b = torch.tensor(2.0)
c = torch.tensor(3.0)
d = torch.tensor(4.0)
e = torch.tensor(5.0)

f = ((a - b + c) * d) / e

print(f)

tensor(1.6000)


In [5]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])

y = torch.sigmoid(x)

print(y)

tensor([0.7311, 0.8808, 0.9526])


In [6]:
import torch.nn.functional as F

x = [-2, -1, 0, 1, 2]
x = torch.tensor(x)
print(F.relu(x))

tensor([0, 0, 0, 1, 2])


In [7]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

tensor(4.)


In [ ]:
import torch

a = torch.tensor(1.0)
b = torch.tensor(2.0)

In [ ]:
a = torch.tensor(1.0)
b = torch.tensor(2.0)
c = torch.tensor(3.0)
d = torch.tensor(4.0)
e = torch.tensor(5.0)

f = ((a - b + c) * d) / e

print(f)

In [ ]:
import torch.nn.functional as F

x = torch.tensor([-2, -1, 0, 1, 2])

print(F.relu(x))
print(torch.sigmoid(x))

In [ ]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2

y.backward()

print(x.grad)

In [8]:
import torch
import torch.nn.functional as F

x = [-2, -1, 0, 1, 2]

x = torch.tensor(x, dtype=torch.float32)

relu_out = F.relu(x)
sigmoid_out = torch.sigmoid(relu_out)

print(relu_out)
print(sigmoid_out)

tensor([0., 0., 0., 1., 2.])
tensor([0.5000, 0.5000, 0.5000, 0.7311, 0.8808])


In [9]:
import torch
import torch.nn.functional as F

# Input tensor
x = torch.tensor([-2, -1, 0, 1, 2], dtype=torch.float32)

# Activation
relu_out = F.relu(x)
sigmoid_out = torch.sigmoid(x)

print("ReLU:", relu_out)
print("Sigmoid:", sigmoid_out)

# Gradient demo
a = torch.tensor(2.0, requires_grad=True)

y = a ** 2
y.backward()

print("dy/da =", a.grad)

ReLU: tensor([0., 0., 0., 1., 2.])
Sigmoid: tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
dy/da = tensor(4.)


In [12]:
import torch
import torch.nn.functional as F
import numpy as np
from sklearn.metrics import accuracy_score

# hyperparameters
examples = 1000
features = 100
hidden = 10
training_steps = 1000
lr = 0.1

X = np.random.randn(examples, features).astype(np.float32)
y = np.random.randint(0, 2, size=examples).astype(np.float32)

X = torch.tensor(X)
y = torch.tensor(y)

w1 = torch.randn(features, hidden, requires_grad=True)
b1 = torch.zeros(hidden, requires_grad=True)

w2 = torch.randn(hidden, requires_grad=True)
b2 = torch.tensor(0.0, requires_grad=True)

# prediction function
def forward(x):
    p1 = torch.tanh(x @ w1 + b1)
    p2 = torch.sigmoid(p1 @ w2 + b2)
    return p2

# accuracy trước training
with torch.no_grad():
    pred = (forward(X) > 0.5).float()
    print("Accuracy before Training:", accuracy_score(y.numpy(), pred.numpy()))

# training loop
for i in range(training_steps):

    p2 = forward(X)

    # binary cross entropy
    error = F.binary_cross_entropy(p2, y)

    # L2 regularization
    loss = error + 0.01 * (torch.sum(w1**2) + torch.sum(w2**2))

    loss.backward()

    # update parameters (gradient descent)
    with torch.no_grad():
        w1 -= lr * w1.grad
        b1 -= lr * b1.grad
        w2 -= lr * w2.grad
        b2 -= lr * b2.grad

        w1.grad.zero_()
        b1.grad.zero_()
        w2.grad.zero_()
        b2.grad.zero_()

# accuracy sau training
with torch.no_grad():
    pred = (forward(X) > 0.5).float()
    print("Accuracy after Training:", accuracy_score(y.numpy(), pred.numpy()))

Accuracy before Training: 0.469
Accuracy after Training: 0.71


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

# Dataset
dataset = torch.tensor([
    [2.7810836,2.550537003,0],
    [1.465489372,2.362125076,0],
    [3.396561688,4.400293529,0],
    [1.38807019,1.850220317,0],
    [3.06407232,3.005305973,0],
    [7.627531214,2.759262235,1],
    [5.332441248,2.088626775,1],
    [6.922596716,1.77106367,1],
    [8.675418651,-0.242068655,1],
    [7.673756466,3.508563011,1]
], dtype=torch.float32)

X = dataset[:, :2]
y = dataset[:, 2].long()

# Model (2 inputs → 2 hidden → 2 outputs)
model = nn.Sequential(
    nn.Linear(2, 2),
    nn.Sigmoid(),
    nn.Linear(2, 2),
    nn.Sigmoid()
)

# Loss + optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.5)

# Training
epochs = 20
for epoch in range(epochs):

    outputs = model(X)
    loss = criterion(outputs, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f">epoch={epoch}, error={loss.item():.3f}")

for name, param in model.named_parameters():
    print(name, param.data)

>epoch=0, error=0.715
>epoch=1, error=0.714
>epoch=2, error=0.713
>epoch=3, error=0.711
>epoch=4, error=0.710
>epoch=5, error=0.709
>epoch=6, error=0.708
>epoch=7, error=0.707
>epoch=8, error=0.706
>epoch=9, error=0.705
>epoch=10, error=0.704
>epoch=11, error=0.703
>epoch=12, error=0.703
>epoch=13, error=0.702
>epoch=14, error=0.701
>epoch=15, error=0.701
>epoch=16, error=0.700
>epoch=17, error=0.699
>epoch=18, error=0.699
>epoch=19, error=0.698
0.weight tensor([[ 0.7668, -0.5317],
        [-0.5599, -0.6209]])
0.bias tensor([0.0695, 0.5406])
2.weight tensor([[ 0.2797, -0.2919],
        [ 0.0985, -0.5231]])
2.bias tensor([-0.4691,  0.1706])
